---
parserOptions:
    ecmaVersion: 2017

env:
    es6: true

rules:
    quotes:
        - error
        - single
    prettier/prettier: 2

plugins:
    - prettier

extends:
    - airbnb-base
    - plugin:prettier/recommended
    - prettier
